name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust to your Node.js version

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test

      - name: Build Docker image
        run: |
          docker build -t payment-gateway .
          docker tag payment-gateway <your-docker-username>/payment-gateway:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push <your-docker-username>/payment-gateway:latest

      - name: Deploy to server (example)
        run: |
          ssh user@server 'docker pull <your-docker-username>/payment-gateway:latest'
          ssh user@server 'docker stop payment-gateway && docker run -d -p 5000:5000 <your-docker-username>/payment-gateway:latest'
